# Generated by Django 2.0.3 on 2018-04-25 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=225, unique=True)),
                ('isDeveloper', models.BooleanField(default=False)),
                ('isPlayer', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('emailConfirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_url', models.URLField(default='', unique=True)),
                ('name', models.CharField(max_length=225, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_currency', models.CharField(default='€', max_length=3)),
                ('developer_name', models.CharField(default='UNKNOWN', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_score', to='gameStore.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameState', models.CharField(max_length=2048)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_save', to='gameStore.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('totPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='pending', max_length=225)),
                ('games', models.ManyToManyField(blank=True, related_name='salesGame', to='gameStore.Game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesPlayer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(related_name='games', to='gameStore.Game'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopcartGames',
            field=models.ManyToManyField(related_name='shopcartGames', to='gameStore.Game'),
        ),
        migrations.AlterUniqueTogether(
            name='gamestate',
            unique_together={('game', 'player')},
        ),
    ]
